project:
  type: website
  output-dir: _site

website: 
  navbar: 
    right: 
      - text: "**notebook**"
        href: /

metadata-files:
  - system/fragments/default-header.yml
  - system/fragments/default-theme.yml
  - system/fragments/default-website.yml
  - system/fragments/notebook-header.yml
  - system/fragments/notebook-theme.yml
  - system/fragments/notebook-website.yml
  - system/fragments/main-navbar-en.yml
  - system/fragments/lang-en.yml