project:
  type: website
  output-dir: _site

website: 
  navbar: 
    right: 
      - text: "**notebook**"
        href: /

metadata-files:
  - system/fragments/default.yml
  - system/fragments/notebook.yml
  - system/fragments/lang-en.yml